### ISSUE TITLE
OAS Security Schemes?

### ISSUE THREAD

**Issue by shayne-neighborlysoftware** [zuplo/zudoku#695]
Currently evaluating Zudoku for use in a production application. I'm aware this is currently in beta but seems very promising, and even if it isn't an option now, would love to return to it once it has matured more.

We have an Open API Spec with our Security Schemes defined, however they are not displayed or usable. Is this just not how Zudoku is intended to work, is it on the roadmap, or am I missing some configuration?

**Comment by mosch** [comment]
Hey @shayne-neighborlysoftware thanks – its great to hear you find Zudoku promising! 
Security Schemes totally are in our backlog and we'd love to learn more about your use-case. Any chance you can post your security schema here so we have something to start?

**Comment by shayne-neighborlysoftware** [comment]
Sure thing! Our minimum viable use case is OAuth 2.0 Client Credentials flow, though we may expand in the future. Here's an example of the type of Scheme we'd be using minus our specific configurations.

``` yaml
securitySchemes:
     OAuthExample:
      description: OAuth2 Client Credentials
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://api.example.com/oauth/token
          scopes:
            https://api.example.com/API/.default: Default scope
```

Then it would be used like this

``` yaml
security:
   - OAuthExample:
      - https://api.example.com/API/.default
```
