### ISSUE TITLE
tagGroups functionality

### ISSUE THREAD

**Issue by timmyGr** [zuplo/zudoku#880]
Redocly has an `x-tagGroups` extension. https://redocly.com/docs-legacy/api-reference-docs/specification-extensions/x-tag-groups

example:

```
x-tagGroups:
  - name: Records
    tags:
      - Record
      - Record Applicant
      - Record Guests
      - Record Locations
      - Record Form
      - Record Attachments
```

So the user would see the sidebar item "Records", expand that, then see the following tags, and then expand those to see the endpoints. We have a massive amount of routes and functionality similar to this would clean up the UI immensely.

Thank you!
